<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Campaigns2.aspx.cs" Inherits="DnD_Project.Campaigns2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script type="text/javascript">
        $(function () {
            $('[id*=Campaigns]').prepend($("<thead></thead>").append($(this).find("tr:first"))).DataTable({
                "responsive": true,
                "sPaginationType": "full_numbers"
            });
        });
    </script>
 
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:GridView ID="Campaigns" runat="server" AllowSorting="true" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false" AllowPaging="true">
            <Columns>
                <asp:BoundField DataField="Campaign Name" HeaderText="Campaign Name" />
                <asp:BoundField DataField="DM" HeaderText="DM" />
            </Columns>
            <HeaderStyle CssClass="gridHeader" />
            <PagerStyle CssClass="gridFooter" />
        </asp:GridView>
    </div>
    </form>
</body>
</html>
